<?php
return [
    'paths' => [
        'ket-qua-xo-so-mien-bac' => 'XSMB',
        'ket-qua-xo-so-mien-nam' => 'XSMN',
        'ket-qua-xo-so-mien-trung' => 'XSMT',
        'ket-qua-xo-so-ha-noi' => 'XSMB',
        'ket-qua-xo-so-thai-binh' => 'XSMB',
        'ket-qua-xo-so-nam-dinh' => 'XSMB',
        'ket-qua-xo-so-bac-ninh' => 'XSMB',
        'ket-qua-xo-so-hai-phong' => 'XSMB',
        'ket-qua-xo-so-quang-ninh' => 'XSMB',
        'ket-qua-xo-so-tp-hcm' => 'XSMN',
        'ket-qua-xo-so-dong-thap' => 'XSMN',
        'ket-qua-xo-so-ca-mau' => 'XSMN',
        'ket-qua-xo-so-ben-tre' => 'XSMN',
        'ket-qua-xo-so-vung-tau' => 'XSMN',
        'ket-qua-xo-so-bac-lieu' => 'XSMN',
        'ket-qua-xo-so-dong-nai' => 'XSMN',
        'ket-qua-xo-so-can-tho' => 'XSMN',
        'ket-qua-xo-so-soc-trang' => 'XSMN',
        'ket-qua-xo-so-tay-ninh' => 'XSMN',
        'ket-qua-xo-so-an-giang' => 'XSMN',
        'ket-qua-xo-so-binh-thuan' => 'XSMN',
        'ket-qua-xo-so-vinh-long' => 'XSMN',
        'ket-qua-xo-so-binh-duong' => 'XSMN',
        'ket-qua-xo-so-tra-vinh' => 'XSMN',
        'ket-qua-xo-so-long-an' => 'XSMN',
        'ket-qua-xo-so-hau-giang' => 'XSMN',
        'ket-qua-xo-so-binh-phuoc' => 'XSMN',
        'ket-qua-xo-so-tien-giang' => 'XSMN',
        'ket-qua-xo-so-kien-giang' => 'XSMN',
        'ket-qua-xo-so-da-lat' => 'XSMN'
    ],

    'weekMaps' => [
        0 => 'Chủ Nhật',
        1 => 'Thứ 2',
        2 => 'Thứ 3',
        3 => 'Thứ 4',
        4 => 'Thứ 5',
        5 => 'Thứ 6',
        6 => 'Thứ 7',
    ]
];
