<?php
return [
    'paths' => [
        'ket-qua-xo-so-mien-bac' => 'XSMB',
        'ket-qua-xo-so-mien-nam' => 'XSMN',
        'ket-qua-xo-so-mien-trung' => 'XSMT',
        'ket-qua-xo-so-ha-noi' => 'XSMB',
        'ket-qua-xo-so-thai-binh' => 'XSMB',
        'ket-qua-xo-so-nam-dinh' => 'XSMB',
        'ket-qua-xo-so-bac-ninh' => 'XSMB',
        'ket-qua-xo-so-hai-phong' => 'XSMB',
        'ket-qua-xo-so-quang-ninh' => 'XSMB',
        'ket-qua-xo-so-tp-hcm' => 'XSMN',
        'ket-qua-xo-so-dong-thap' => 'XSMN',
        'ket-qua-xo-so-ca-mau' => 'XSMN',
        'ket-qua-xo-so-ben-tre' => 'XSMN',
        'ket-qua-xo-so-vung-tau' => 'XSMN',
        'ket-qua-xo-so-bac-lieu' => 'XSMN',
        'ket-qua-xo-so-dong-nai' => 'XSMN',
        'ket-qua-xo-so-can-tho' => 'XSMN',
        'ket-qua-xo-so-soc-trang' => 'XSMN',
        'ket-qua-xo-so-tay-ninh' => 'XSMN',
        'ket-qua-xo-so-an-giang' => 'XSMN',
        'ket-qua-xo-so-binh-thuan' => 'XSMN',
        'ket-qua-xo-so-vinh-long' => 'XSMN',
        'ket-qua-xo-so-binh-duong' => 'XSMN',
        'ket-qua-xo-so-tra-vinh' => 'XSMN',
        'ket-qua-xo-so-long-an' => 'XSMN',
        'ket-qua-xo-so-hau-giang' => 'XSMN',
        'ket-qua-xo-so-binh-phuoc' => 'XSMN',
        'ket-qua-xo-so-tien-giang' => 'XSMN',
        'ket-qua-xo-so-kien-giang' => 'XSMN',
        'ket-qua-xo-so-da-lat' => 'XSMN',
        'ket-qua-xo-so-thua-thien-hue' => 'XSMT',
        'ket-qua-xo-so-phu-yen' => 'XSMT',
        'ket-qua-xo-so-quang-nam' => 'XSMT',
        'ket-qua-xo-so-dac-lac' => 'XSMT',
        'ket-qua-xo-so-da-nang' => 'XSMT',
        'ket-qua-xo-so-khanh-hoa' => 'XSMT',
        'ket-qua-xo-so-binh-dinh' => 'XSMT',
        'ket-qua-xo-so-quang-binh' => 'XSMT',
        'ket-qua-xo-so-quang-tri' => 'XSMT',
        'ket-qua-xo-so-qia-lai' => 'XSMT',
        'ket-qua-xo-so-ninh-thuan' => 'XSMT',
        'ket-qua-xo-so-quang-ngai' => 'XSMT',
        'ket-qua-xo-so-dac-nong' => 'XSMT',
        'ket-qua-xo-so-kon-tum' => 'XSMT'
    ],

    'weekMaps' => [
        0 => 'Chủ Nhật',
        1 => 'Thứ 2',
        2 => 'Thứ 3',
        3 => 'Thứ 4',
        4 => 'Thứ 5',
        5 => 'Thứ 6',
        6 => 'Thứ 7',
    ],

    'weekMapsEN' => [
        0 => 'Sunday',
        1 => 'Monday',
        2 => 'TuesDay',
        3 => 'Wednesday',
        4 => 'Thursday',
        5 => 'Friday',
        6 => 'Saturday',
    ]
];
